// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink/index.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Item: typeof import('./components/Sidebar/Item.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    Link: typeof import('./components/AppLink/Link.vue')['default']
    Logo: typeof import('./components/Sidebar/Logo.vue')['default']
    Main: typeof import('./components/Main/index.vue')['default']
    Navbar: typeof import('./components/Navbar/index.vue')['default']
    ScrollPane: typeof import('./components/TagsView/ScrollPane.vue')['default']
    Sidebar: typeof import('./components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./components/Sidebar/SidebarItem.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./components/TagsView/index.vue')['default']
    UserHeader: typeof import('./components/Header/userHeader.vue')['default']
  }
}

export { }
